// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeT2wfHmZu12vBE5UQvR0lGACp7aUnu2g',
    appId: '1:877776417555:web:4adb543841934b6f2d20e6',
    messagingSenderId: '877776417555',
    projectId: 'ncs-shine',
    authDomain: 'ncs-shine.firebaseapp.com',
    storageBucket: 'ncs-shine.firebasestorage.app',
    measurementId: 'G-S7NXCCV9JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaG6Vpq8A6nGparj9Ij3a1ryBPNNJ9jos',
    appId: '1:877776417555:android:3bde31cc8d9723472d20e6',
    messagingSenderId: '877776417555',
    projectId: 'ncs-shine',
    storageBucket: 'ncs-shine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7uMepDAktt3q9dHpFppG0j2TYUrNkWxc',
    appId: '1:877776417555:ios:5c26da917a6f79ab2d20e6',
    messagingSenderId: '877776417555',
    projectId: 'ncs-shine',
    storageBucket: 'ncs-shine.firebasestorage.app',
    iosBundleId: 'com.example.ncsNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7uMepDAktt3q9dHpFppG0j2TYUrNkWxc',
    appId: '1:877776417555:ios:5c26da917a6f79ab2d20e6',
    messagingSenderId: '877776417555',
    projectId: 'ncs-shine',
    storageBucket: 'ncs-shine.firebasestorage.app',
    iosBundleId: 'com.example.ncsNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeT2wfHmZu12vBE5UQvR0lGACp7aUnu2g',
    appId: '1:877776417555:web:4adb543841934b6f2d20e6',
    messagingSenderId: '877776417555',
    projectId: 'ncs-shine',
    authDomain: 'ncs-shine.firebaseapp.com',
    storageBucket: 'ncs-shine.firebasestorage.app',
    measurementId: 'G-S7NXCCV9JH',
  );
}
